name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      if: runner.os != 'Linux'

    - name: Run tests
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Package extension
      run: npx @vscode/vsce package -o "agntcy-dir-${{ github.sha }}.vsix"

    - name: Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: agntcy-dir-${{ github.sha }}
        path: "*.vsix"
